### ISSUE TITLE
Drones won't move

### ISSUE THREAD

**Issue by quinn-n** [KosmosPrime/OpenComputers#11]
Drones refuse to move. I don't have any power mods installed, and I have `ignorePower=true` in the config.

The following test code makes drones move on the original OpenComputers in 1.12.2, but won't move them on your fork in 1.16.5.

```
local drone = component.proxy(component.list("drone")())

local function move(dx, dy, dz)
  drone.move(dx, dy, dz)
  while drone.getOffset() > 0.5 do
    drone.setStatusText(tostring(drone.getOffset()))
    computer.pullSignal(0.2)
  end
end

while true do
  move(10, 0, 0)
  move(-10, 0, 0)
end
```

**Comment by KosmosPrime** [comment]
I'm unable to reproduce this, with and without `ignorePower` the drone moves just fine - if activated with shift-click, that is. Pushing the power button makes it go to `0, 0, 0` instead, but I understand that's not what you're seeing.
Please double-check that you're using the 1.8.3 release (instead of a snapshot version) and describe your setup/results in more detail (e.g. are you using a wireless bootloader).

**Comment by quinn-n** [comment]
I added this mod to a pack I'm playing on with some friends, and one of the mods in the pack picks up entities with shift-click. So I'd been starting drones with the power button the whole time. When I tested the mod on its own I did the same thing. I rebound the other mod so I can shift-click the drone and it moves normally. Thanks for the help.

PEBKAC
