### ISSUE TITLE
Floppy much darker than OC 1.12.2

### ISSUE THREAD

**Issue by Bumer-32** [KosmosPrime/OpenComputers#18]
OC 1.12.2
![image](https://github.com/KosmosPrime/OpenComputers/assets/79054301/cb6f14c9-53b9-4696-9eb3-4ad3ae109b55)

OC 1.16.5
![image](https://github.com/KosmosPrime/OpenComputers/assets/79054301/28a0f27b-7226-4f6c-8839-1708feab5600)

**Comment by KosmosPrime** [comment]
Part of this was because OC liberally uses render scaling operations with negative values. This causes normals (used for lighting and shading) to be wildly incorrect due to a mistake/oversight in vanilla code. If you notice something appearing a little too dark and without shading differences, please don't hesitate to report it.
