### ISSUE TITLE
Exception message: java.lang.NoSuchFieldError: LOOT_FUNCTION_TYPE

### ISSUE THREAD

**Issue by theotheroracle** [KosmosPrime/OpenComputers#9]
built the latest from the dev branch, got this error when tryng to run minecraft

**Comment by KosmosPrime** [comment]
You're getting this error because you're running an unobfuscated version of the mod in an obfuscated environment. If you're using a JAR with the official client/forge, make sure that you've included the `remapJar` step during your build. If using the gradle environment, check that the environment is deobfuscated and uses dev dependencies.
I cannot reproduce this on 2abad02e. Note that `git pull` and others will not delete files you've _added_, which may also be the cause of this issue.

In the future, please include more information about how you got the exception as well as (at least) a full stack trace.

**Comment by theotheroracle** [comment]
alright, sorry about that

**Comment by theotheroracle** [comment]
i cleaned up the git directory and ran gradlew build a few more times and eventually it built successfully, thanks for the help
